#!/bin/bash

echo "Data Directory: $OPENSHIFT_DATA_DIR"
if [ ! -f "$OPENSHIFT_DATA_DIR"secrets.json ]; then
	echo "Generating $OPENSHIFT_DATA_DIR/secrets.json"
	python "$OPENSHIFT_REPO_DIR"libs/secrets.py > "$OPENSHIFT_DATA_DIR"secrets.json
fi

echo "Executing 'python $OPENSHIFT_REPO_DIR/manage.py migrate --noinput'"
python "$OPENSHIFT_REPO_DIR"manage.py migrate --noinput

echo "Executing 'python $OPENSHIFT_REPO_DIR/manage.py collectstatic --noinput'"
python "$OPENSHIFT_REPO_DIR"manage.py collectstatic --noinput

cd "$OPENSHIFT_REPO_DIR"

echo "Executing: '$VIRTUAL_ENV/bin/activate'"
source $VIRTUAL_ENV/bin/activate

python --version

echo "Executing 'python $VIRTUAL_ENV/bin/celery multi start worker -A excel_viewer --logfile="$OPENSHIFT_LOG_DIR/celery.log"'"
python $VIRTUAL_ENV/bin/celery multi start worker -A excel_viewer --logfile="$OPENSHIFT_LOG_DIR/celery.log"