#!/bin/bash
cd "$OPENSHIFT_REPO_DIR"

echo "Executing '$VIRTUAL_ENV/bin/activate'"
source $VIRTUAL_ENV/bin/activate

echo "Executing 'python $VIRTUAL_ENV/bin/celery multi stop worker'"
python $VIRTUAL_ENV/bin/celery multi stop worker