language: python
python:
  - 3.3

services: postgresql

env:
  global:
   - OPENSHIFT_POSTGRESQL_DB_URL="postgres://postgres:@localhost"
   - OPENSHIFT_APP_NAME="travisdb"
   - DJANGO_SETTINGS_MODULE="excel_viewer.settings"
   - PYTHONPATH="/home/travis/build/emoitzi/django-excel-viewer"

install :
  - pip install -r excel_viewer/requirements.txt
  - pip install coveralls
before_script:
  - psql -c "CREATE DATABASE travisdb;" -U  postgres
script:
  - python manage.py migrate
  - python manage.py test
after_success:
  coveralls
