# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 11:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinate', models.CharField(max_length=2)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('color_name', models.CharField(max_length=20)),
                ('row_span', models.IntegerField(blank=True, null=True, validators=django.core.validators.MinValueValidator(1))),
                ('column_span', models.IntegerField(blank=True, null=True, validators=django.core.validators.MinValueValidator(1))),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentColors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=6)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_import.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_import.Document')),
            ],
        ),
        migrations.AddField(
            model_name='cell',
            name='row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_import.Row'),
        ),
        migrations.AlterUniqueTogether(
            name='documentcolors',
            unique_together=set([('name', 'document')]),
        ),
    ]
