# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_import', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='horizontal_alignment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cell',
            name='value',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
